Repository KanCraft/kanColleWidget, pull requests merged in 2020-08, with the labels that each got.

#1159 ダッシュボードのアイコンを錨とカメラで切り替える
  src/js/Applications/Components/Dashboard/ClockView/index.tsx
  src/js/Applications/Components/Dashboard/index.tsx
Labels: 改善

#1160 スクショのキーボードショートカットとかその他もろもろ
  dest/img/widget-chang.png
  manifest.json
  src/css/entrypoints/dashboard.scss
  src/css/entrypoints/options.scss
  src/js/Applications/Background/Controllers/Command/index.ts
  src/js/Applications/Background/Controllers/Message/Capture.ts
  src/js/Applications/Background/Controllers/Message/Window.ts
  src/js/Applications/Background/Cron/index.ts
  src/js/Applications/Background/Routers/Command.ts
  src/js/Applications/Components/Dashboard/ClockView/index.tsx
  src/js/Applications/Components/Options/Announce/index.tsx
  src/js/Applications/Components/Options/Notifications/index.tsx
  src/js/Applications/Components/Options/Screenshot/index.tsx
  src/js/Applications/Components/Options/index.tsx
  src/js/Applications/Components/Popup/IconMenu.tsx
  src/js/Applications/Models/Settings/NotificationSetting.ts
  src/js/Applications/Models/Settings/ScreenshotSetting.ts
  src/js/Services/Download/index.ts
  src/js/Services/Notification.ts
  src/js/entrypoints/background.ts
Labels: 不具合・バグ, 改善, 機能要望

#1162 画像アーカイブの復活
  dest/html/archive.html
  src/css/entrypoints/archive.scss
  src/js/Applications/Background/Controllers/Message/Window.ts
  src/js/Applications/Background/Routers/Message.ts
  src/js/Applications/Components/Archive/index.tsx
  src/js/Applications/Components/Capture/index.tsx
  src/js/Applications/Components/Popup/IconMenu.tsx
  src/js/Applications/Models/Scrap.ts
  src/js/Services/Window.ts
  src/js/entrypoints/archive.tsx
  webpack.config.js
Labels: 改善, 機能要望

#1163 前回の窓サイズと位置を記憶する修正と、残り時間表示の追加
  src/js/Applications/Background/Controllers/Message/Window.ts
  src/js/Applications/Components/Dashboard/QueuesView/MatrixView.tsx
  src/js/Applications/Components/Dashboard/QueuesView/TirednessView.tsx
  src/js/Applications/Components/Options/DashboardDesign/index.tsx
  src/js/Applications/Components/Options/index.tsx
  src/js/Applications/Context/DMM.ts
  src/js/Applications/Models/Frame.ts
  src/js/Applications/Models/Settings/TimerDisplaySetting.ts
  src/js/Services/Window.ts
  src/js/entrypoints/dmm.ts
  src/js/entrypoints/global-pollution.ts
Labels: 改善, 機能要望

#1167 出撃するとダッシュボードが真っ白になる問題の修正
  src/js/Applications/Components/Dashboard/QueuesView/TirednessView.tsx
Labels: 不具合・バグ

#1169 スクショ・ミュートボタンをちょっと大きくする、音声のみ通知、スクショ編集にマスク機能追加、など
  .github/workflows/webstore-prod.yml
  ISSUE_TEMPLATE.md
  src/css/entrypoints/capture.scss
  src/js/Applications/Background/Controllers/Meta/index.ts
  src/js/Applications/Background/Cron/index.ts
  src/js/Applications/Components/Capture/Tools/DrawToolBase.ts
  src/js/Applications/Components/Capture/Tools/Rect.ts
  src/js/Applications/Components/Capture/index.tsx
  src/js/Applications/Components/Dashboard/QueuesView/TirednessView.tsx
  src/js/Applications/Components/Options/Notifications/index.tsx
  src/js/Applications/Context/Features/InAppButtons.ts
  src/js/Services/Notification.ts
  src/js/Services/Sound/index.ts
Labels: 改善, 機能要望

#1183 艦これウィジェットちゃんをもっと自動化するやつ
  .github/workflows/egosearch.yml
  scripts/egosearch.js
Labels: 改善

#1192 forkしたリポジトリでActionsを実行しない方法を記載
  CONTRIBUTING.md
Labels: 改善

#1197 戦闘終了から戦果が表示されるまで艦隊状況のスクショを撮らない対応、など
  src/js/Applications/Background/Controllers/Meta/index.ts
  src/js/Applications/Background/Controllers/Runtime/index.ts
  src/js/Applications/Background/Routers/Runtime.ts
  src/js/Applications/Context/Features/DamageSnapshot.ts
  src/js/entrypoints/background.ts
  tests/Applications/Background/Controllers/Meta.spec.ts
  tests/Applications/Background/Controllers/Runtime.spec.ts
  tests/Applications/Background/Routers/Runtime.spec.ts
Labels: 改善
