Repository KanCraft/kanColleWidget, pull requests merged in 2020-10, with the labels that each got.

#1226 新しい遠征のデータを追加(2020年9月)
  src/js/Applications/Models/Queue/missions.ts
Labels: 改善

#1230 ゲーム窓サイズ設定の＋ボタンが反応しないことのある不具合の修正
  src/js/Applications/Components/Options/Frames/index.tsx
Labels: 不具合・バグ

#1231 海域名 (1-6, 7-2, 7-3) を追加
  src/js/Applications/Models/Sortie/catalog.ts
Labels: 不具合・バグ, 改善

#1228 支援艦隊の遠征を出した際に非通知にできるようにする
  src/js/Applications/Background/Controllers/Request/Mission.ts
  src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
  src/js/Applications/Components/Options/Notifications/index.tsx
  src/js/Applications/Components/Options/ResetButton.tsx
  src/js/Applications/Components/Options/SectionTitle.tsx
  src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
Labels: 改善

#1227 ツイッター連携機能
  .github/workflows/webstore-prod.yml
  .github/workflows/webstore-stage.yml
  .gitignore
  config/example/firebase.json
  config/example/twitter.json
  manifest.json
  package-lock.json
  package.json
  src/css/entrypoints/popup.scss
  src/js/Applications/Components/Capture/Tweet/Modal.tsx
  src/js/Applications/Components/Capture/index.tsx
  src/js/Applications/Components/Options/TwitterAccount/index.tsx
  src/js/Applications/Components/Options/index.tsx
  src/js/Applications/Components/Popup/IconMenu.tsx
  src/js/Applications/Components/Popup/LaunchTrigger.tsx
  src/js/Applications/Components/Popup/OfficialTwitter.tsx
  src/js/Applications/Components/Popup/index.tsx
  src/js/Applications/Models/Settings/TwitterSetting.ts
  src/js/Services/API/Twitter.ts
  src/js/entrypoints/background.ts
  src/js/entrypoints/popup.tsx
  webpack.config.js
Labels: 改善, 機能要望
